### ISSUE TITLE
Crash when run api.js

### ISSUE THREAD

**Issue by soleimanim** [shadowsocks/shadowsocks-hub-api#3]
I followed steps of documentation to start shadow socks hub nut I get the following crash log.

        throw new Error('Mode must be "sandbox" or "live"');
        ^

`Error: Mode must be "sandbox" or "live"
    at Object.configure (/root/shadowsocks-hub-api/node_modules/paypal-rest-sdk/lib/api.js:26:15)
    at Object.configure (/root/shadowsocks-hub-api/node_modules/paypal-rest-sdk/lib/paypal-rest-sdk.js:10:13)
    at Object.regeneratorRuntime.mark.regeneratorRuntime.wrap.e.prev (/root/shadowsocks-hub-api/api.js:6037:7)
    at t (/root/shadowsocks-hub-api/api.js:10:21)
    at Object.<anonymous> (/root/shadowsocks-hub-api/api.js:1359:23)
    at t (/root/shadowsocks-hub-api/api.js:10:21)
    at Object.regeneratorRuntime.mark.regeneratorRuntime.wrap.e.prev (/root/shadowsocks-hub-api/api.js:6228:23)
    at t (/root/shadowsocks-hub-api/api.js:10:21)
    at Object.<anonymous> (/root/shadowsocks-hub-api/api.js:11026:23)
    at t (/root/shadowsocks-hub-api/api.js:10:21)
    at Object.<anonymous> (/root/shadowsocks-hub-api/api.js:11034:13)
    at t (/root/shadowsocks-hub-api/api.js:10:21)
    at Object.regeneratorRuntime.mark.regeneratorRuntime.wrap.e.prev (/root/shadowsocks-hub-api/api.js:11041:13)
    at t (/root/shadowsocks-hub-api/api.js:10:21)
    at Object.<anonymous> (/root/shadowsocks-hub-api/api.js:13600:13)
    at t (/root/shadowsocks-hub-api/api.js:10:21)`

**Comment by Eggham** [comment]
Thanks mate! It was due to the inconsistent dev and production environments on my machine.

The has been fixed. Please keep more bug report coming... ;-)
